Traceback (most recent call last):
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\krstig\.conda\envs\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\krstig\.conda\envs\python37\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
plt.ion()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mOSError[0m                                   Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_4588\2191868119.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0mrcParams[0m[1;33m,[0m [0mcycler[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0mplt[0m[1;33m.[0m[0mion[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m    102[0m [1;32mimport[0m [0mwarnings[0m[1;33m[0m[1;33m[0m[0m
[0;32m    103[0m [1;33m[0m[0m
[1;32m--> 104[1;33m [1;32mimport[0m [0mnumpy[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    105[0m [1;32mfrom[0m [0mpackaging[0m[1;33m.[0m[0mversion[0m [1;32mimport[0m [0mparse[0m [1;32mas[0m [0mparse_version[0m[1;33m[0m[1;33m[0m[0m
[0;32m    106[0m [1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m    146[0m [1;33m[0m[0m
[0;32m    147[0m     [1;31m# Allow distributors to run custom init code[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 148[1;33m     [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0m_distributor_init[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    149[0m [1;33m[0m[0m
[0;32m    150[0m     [1;32mfrom[0m [1;33m.[0m [1;32mimport[0m [0mcore[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py[0m in [0;36m<module>[1;34m[0m
[0;32m     24[0m                 [1;31m# NOTE: would it change behavior to load ALL[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m     25[0m                 [1;31m# DLLs at this path vs. the name restriction?[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 26[1;33m                 [0mWinDLL[0m[1;33m([0m[0mos[0m[1;33m.[0m[0mpath[0m[1;33m.[0m[0mabspath[0m[1;33m([0m[0mfilename[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     27[0m                 [0mDLL_filenames[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mfilename[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m     28[0m         [1;32mif[0m [0mlen[0m[1;33m([0m[0mDLL_filenames[0m[1;33m)[0m [1;33m>[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\.conda\envs\python37\lib\ctypes\__init__.py[0m in [0;36m__init__[1;34m(self, name, mode, handle, use_errno, use_last_error)[0m
[0;32m    362[0m [1;33m[0m[0m
[0;32m    363[0m         [1;32mif[0m [0mhandle[0m [1;32mis[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 364[1;33m             [0mself[0m[1;33m.[0m[0m_handle[0m [1;33m=[0m [0m_dlopen[0m[1;33m([0m[0mself[0m[1;33m.[0m[0m_name[0m[1;33m,[0m [0mmode[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    365[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    366[0m             [0mself[0m[1;33m.[0m[0m_handle[0m [1;33m=[0m [0mhandle[0m[1;33m[0m[1;33m[0m[0m

[1;31mOSError[0m: [WinError 193] %1 er ikke et gyldig Win32-program
OSError: [WinError 193] %1 er ikke et gyldig Win32-program

